### ISSUE TITLE
Replace all "Internal Server Error" with "Authorization Error"

### ISSUE THREAD

**Issue by gruz0** [optriment/optrispace-frontend#227]
We used incorrect error description in pages (`./src/pages`).

It would be good to replace all messages with "Internal Server Error" with more descriptive like "Authorization Error" for the code like this:

```js
<ErrorWrapper header="Internal Server Error" error={...} />
```

**Comment by rabbanirizwan** [comment]
@gruz0 can you assign me this issue
Can you also tell me if we are passing a static value or if there is any functionality that we can use to confirm that it is an internal server or authorization error?

**Comment by gruz0** [comment]
> @gruz0 can you assign me this issue
> 
> Can you also tell me if we are passing a static value or if there is any functionality that we can use to confirm that it is an internal server or authorization error?

Hi!

At this moment it is 100% enough just to replace text messages.

**Comment by rabbanirizwan** [comment]
Kindly assign me this issue

**Comment by gruz0** [comment]
@rabbanirizwan you can take it 🤘

**Comment by rabbanirizwan** [comment]
@gruz0  kindly review this branch
https://github.com/optriment/optrispace-frontend/pull/234

**Comment by gruz0** [comment]
Done 👍
